---
apiVersion: v1
kind: flag-configuration

flag: default.score

enabled: false

defaultValue: false

conditions:
  - allOf:
      - property:
          name: isBetaUser
          operator: is-true
    flagValue: true
