---
apiVersion: v1
kind: flag-configuration

flag: default.headerColor

enabled: true

defaultValue: - percentage: 50
  option: is-dark
- percentage: 50
  option: is-primary
- percentage: 0
  option: is-white

conditions:
  []
